"use client";

import type React from "react";

import { useState, useEffect } from "react";
import {
  BookOpen,
  Loader2,
  Send,
  Download,
  Clock,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";
import jsPDF from "jspdf";

interface HistoryItem {
  id: string;
  topic: string;
  output: string;
  timestamp: number;
}

export default function Home() {
  const [topic, setTopic] = useState("");
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedHistory = localStorage.getItem("studyHistory");
    if (savedHistory) {
      try {
        setHistory(JSON.parse(savedHistory));
      } catch (error) {
        console.error("Failed to load history:", error);
      }
    }
  }, []);

  useEffect(() => {
    if (mounted && history.length > 0) {
      localStorage.setItem("studyHistory", JSON.stringify(history));
    }
  }, [history, mounted]);

  const suggestedTopics = [
    "Photosynthesis in plants",
    "Water cycle",
    "Human body systems",
    "Ecosystems and biodiversity",
  ];

  const handleGenerate = async () => {
    if (!topic.trim()) return alert("Enter this topic!");
    setLoading(true);
    setOutput("");

    try {
      const res = await fetch("http://localhost:5000/api/gemini", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic }),
      });

      const data = await res.json();
      if (data.output) {
        setOutput(data.output);
        const newItem: HistoryItem = {
          id: Date.now().toString(),
          topic: topic,
          output: data.output,
          timestamp: Date.now(),
        };
        setHistory([newItem, ...history.slice(0, 49)]);
      } else setOutput("Error: " + (data.error || "No response"));
    } catch (err) {
      setOutput("Network error. Check if backend is running.");
    } finally {
      setLoading(false);
    }
  };

  const handleSuggestedTopic = (topic: string) => {
    setTopic(topic);
  };

  const handleDownloadPdf = () => {
    if (!output) return;

    setDownloadingPdf(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const textWidth = pageWidth - 2 * margin;

      // Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.text("CBC Smart Study - Lesson Plan", margin, 20);

      // Topic
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 139);
      doc.text(`Topic: ${topic}`, margin, 35);

      // Content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);

      const splitText = doc.splitTextToSize(output, textWidth);
      let yPosition = 50;

      splitText.forEach((line: string) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });

      // Footer
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Generated by CBC Smart Study on ${new Date().toLocaleDateString()}`,
        margin,
        pageHeight - 10
      );

      doc.save(`${topic.replace(/\s+/g, "_")}_lesson_plan.pdf`);
    } catch (error) {
      console.error("PDF generation error:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setDownloadingPdf(false);
    }
  };

  const handleLoadHistory = (item: HistoryItem) => {
    setTopic(item.topic);
    setOutput(item.output);
    setShowHistory(false);
  };

  const handleDeleteHistory = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setHistory(history.filter((item) => item.id !== id));
    localStorage.setItem(
      "studyHistory",
      JSON.stringify(history.filter((item) => item.id !== id))
    );
  };

  const handleClearAllHistory = () => {
    if (confirm("Are you sure you want to clear all history?")) {
      setHistory([]);
      localStorage.removeItem("studyHistory");
    }
  };

  const formatDate = (timestamp: number) => {
    const date = new Date(timestamp);
    const today = new Date();
    const isToday = date.toDateString() === today.toDateString();

    if (isToday) {
      return date.toLocaleTimeString("en-US", {
        hour: "2-digit",
        minute: "2-digit",
      });
    }
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  if (!mounted) {
    return <div className="min-h-screen bg-white" />;
  }

  return (
    <main className="min-h-screen bg-white flex">
      {/* Sidebar */}
      <div
        className={`sticky top-0 h-screen w-64 bg-white border-r border-gray-200/50 flex flex-col transition-all duration-300 z-40 ${
          showHistory ? "translate-x-0" : "-translate-x-full md:translate-x-0"
        } md:relative md:w-64 md:-translate-x-0 overflow-hidden`}
      >
        {/* Sidebar Header */}
        <div className="p-4 border-b border-gray-200/50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg">
              <Clock className="w-4 h-4 text-white" />
            </div>
            <h3 className="font-semibold text-sm text-gray-900">History</h3>
          </div>
          <button
            onClick={() => setShowHistory(false)}
            className="md:hidden p-1.5 hover:bg-gray-100 rounded-lg transition"
          >
            <ChevronLeft className="w-4 h-4 text-gray-600" />
          </button>
        </div>

        {/* History Items */}
        <div className="flex-1 overflow-y-auto p-3 space-y-1.5">
          {history.length === 0 ? (
            <div className="text-center py-8">
              <p className="text-sm text-gray-500">No history yet</p>
              <p className="text-xs text-gray-400 mt-1">
                Your lessons will appear here
              </p>
            </div>
          ) : (
            history.map((item) => (
              <button
                key={item.id}
                onClick={() => handleLoadHistory(item)}
                className="w-full text-left p-3 rounded-lg hover:bg-blue-50 group transition-all duration-200 hover:shadow-sm"
              >
                <p className="text-sm font-medium text-gray-800 truncate group-hover:text-blue-600 transition">
                  {item.topic}
                </p>
                <p className="text-xs text-gray-500 mt-1">
                  {formatDate(item.timestamp)}
                </p>
              </button>
            ))
          )}
        </div>

        {/* Clear History Button */}
        {history.length > 0 && (
          <div className="p-3 border-t border-gray-200/50">
            <button
              onClick={handleClearAllHistory}
              className="w-full px-3 py-2 text-xs text-red-600 hover:bg-red-50 rounded-lg transition-colors duration-200 font-medium"
            >
              Clear All
            </button>
          </div>
        )}
      </div>

      {/* Mobile Overlay */}
      {showHistory && (
        <div
          className="fixed inset-0 bg-black/30 md:hidden z-30 transition-opacity"
          onClick={() => setShowHistory(false)}
        />
      )}

      {/* Main Content */}
      <div className="flex-1 flex flex-col">
        {/* Header */}
        <header className="border-b border-gray-200/50 bg-white sticky top-0 z-50 backdrop-blur-sm bg-white/80">
          <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button
                onClick={() => setShowHistory(!showHistory)}
                className="md:hidden p-2 hover:bg-gray-100 rounded-lg transition"
              >
                <ChevronRight className="w-5 h-5 text-gray-600" />
              </button>
              <div className="p-2.5 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl shadow-lg">
                <BookOpen className="w-5 h-5 text-white" />
              </div>
              <div>
                <h1 className="text-lg font-semibold text-gray-900">
                  CBC Smart Study
                </h1>
                <p className="text-xs text-gray-500">
                  AI-powered learning assistant
                </p>
              </div>
            </div>
          </div>
        </header>

        {/* Chat Area */}
        <div className="flex-1 flex flex-col overflow-hidden">
          <div className="max-w-4xl w-full mx-auto px-4 py-8 flex flex-col flex-1 overflow-y-auto">
            {output ? (
              <div className="space-y-6">
                {/* User Message */}
                <div className="flex justify-end animate-in fade-in slide-in-from-bottom-4 duration-500">
                  <div className="bg-blue-600 rounded-3xl rounded-tr-sm px-5 py-3 max-w-xl shadow-sm">
                    <p className="text-sm text-white font-medium">{topic}</p>
                  </div>
                </div>

                {/* Assistant Message */}
                <div className="flex justify-start">
                  <div className="bg-gray-50 rounded-3xl rounded-tl-sm px-5 py-4 max-w-2xl border border-gray-200/50">
                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">
                      {output}
                    </p>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex justify-start gap-3 mt-4">
                  <button
                    onClick={handleDownloadPdf}
                    disabled={downloadingPdf}
                    className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-all duration-200 disabled:opacity-60 disabled:cursor-not-allowed text-sm font-medium shadow-sm hover:shadow-md"
                  >
                    {downloadingPdf ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Generating...
                      </>
                    ) : (
                      <>
                        <Download className="h-4 w-4" />
                        Download PDF
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => {
                      setOutput("");
                      setTopic("");
                    }}
                    className="flex items-center gap-2 px-4 py-2.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-all duration-200 text-sm font-medium"
                  >
                    New Topic
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex-1 flex flex-col items-center justify-center text-center">
                <div className="mb-8 animate-in fade-in duration-500">
                  <div className="w-20 h-20 bg-gradient-to-br from-blue-100 to-blue-50 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg">
                    <BookOpen className="w-10 h-10 text-blue-600" />
                  </div>
                  <h2 className="text-4xl font-bold text-gray-900 mb-3">
                    Start Learning
                  </h2>
                  <p className="text-gray-500 max-w-md text-base">
                    Enter any topic to generate comprehensive study materials
                  </p>
                </div>

                <div className="w-full">
                  <p className="text-sm font-semibold text-gray-600 mb-4">
                    Popular topics:
                  </p>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-w-lg mx-auto">
                    {suggestedTopics.map((t) => (
                      <button
                        key={t}
                        onClick={() => {
                          setTopic(t);
                          setTimeout(() => handleGenerate(), 100);
                        }}
                        className="px-4 py-3 bg-white border border-gray-200 hover:border-blue-400 hover:bg-blue-50 rounded-lg text-sm text-gray-700 hover:text-blue-600 transition-all duration-200 font-medium shadow-sm hover:shadow-md"
                      >
                        {t}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Input Bar */}
        <div className="border-t border-gray-200/50 bg-white sticky bottom-0 backdrop-blur-sm bg-white/80">
          <div className="max-w-4xl w-full mx-auto px-4 py-4">
            <div className="flex gap-3">
              <input
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                onKeyPress={(e) =>
                  e.key === "Enter" && !loading && handleGenerate()
                }
                placeholder="Ask about any topic..."
                disabled={loading}
                className="flex-1 bg-gray-50 border border-gray-200 rounded-full px-5 py-3 text-sm text-gray-900 placeholder:text-gray-500 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 disabled:opacity-50 disabled:bg-gray-100"
              />
              <button
                onClick={handleGenerate}
                disabled={loading || !topic.trim()}
                className="p-3 bg-blue-600 hover:bg-blue-700 text-white rounded-full transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center shadow-md hover:shadow-lg"
              >
                {loading ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  <Send className="h-5 w-5" />
                )}
              </button>
            </div>

            {/* Loading State */}
            {loading && (
              <div className="mt-4 flex items-center gap-2">
                <div className="flex gap-1">
                  <div className="w-2 h-2 bg-blue-600 rounded-full animate-bounce" />
                  <div
                    className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"
                    style={{ animationDelay: "0.1s" }}
                  />
                  <div
                    className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"
                    style={{ animationDelay: "0.2s" }}
                  />
                </div>
                <span className="text-xs text-gray-500 font-medium">
                  Learning from your topic...
                </span>
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
